apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-wlyl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-wlyl@sha256:84e0ed3143df9146cf409e96992eb4aacf231c584ab9480937bdfb075f0c077b
        name: my-python
        resources: {}
status: {}
